# Generated by Django 2.2.5 on 2019-11-19 02:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20191119_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
